language: python

python:
  - '3.7'
  - '3.8'

services:
  - docker

install:
  - make install

script:
  - make test
  - make cov
  - make build

before_deploy:
  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    branch: develop
