language: python

python:
  - '3.7'
  - '3.8'

services:
  - docker

install:
  - make install

script:
  - make test
  - make cov
  - make build

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker login -u $HEROKU_USERNAME -p $HEROKU_PASSWORD registry.heroku.com

deploy:
  provider: heroku
  api_key: $HEROKU_PASSWORD
  app: surname-detection
  script: make release
  skip_cleanup: true
  on:
    branch: develop
