language: python

python:
  - '3.7'
  - '3.8'

services:
  - docker

install:
  - make install

script:
  - make test
  - make cov
  - make build

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_API_KEY"  | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    branch: develop

after_deploy:
  - make release
