os:
  - linux
  - osx
  - windows

language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

addons:
  apt:
    packages:
      - docker-ce

install:
  - Make install

script:
  - Make cov
  - Make build
