language: python

python:
  - '3.7'
  - '3.8'

services:
  - docker

install:
  - make install

script:
  - make test
  - make cov
  - make build

deploy:
  provider: script
  script: make travis_deploy
  skip_cleanup: true
  on:
    branch: develop
